core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    # c помощью функций
    # path('accounts/', views.get_account_list, name='accounts'),
    # path('account_detail/<int:pk>', views.get_account_detail, name='account_detail'),

    path('accounts/', views.AccountList.as_view(), name='accounts'),
    path('account_detail/<int:pk>', views.AccountDetail.as_view(), name='account_detail'),
    path('account_create', views.AccountCreate.as_view(), name='account_create'),
    path('account_update/<int:pk>', views.AccountUpdate.as_view(), name='account_update'),
    path('account_delete/<int:pk>', views.AccountDelete.as_view(), name='account_delete'),
    path('', views.get_main_page, name='main'),
]

home7/urls.py
from django.contrib import admin
from django.urls import path, include
from .yasg import urlpatterns as doc_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core'))
]

urlpatterns += doc_urls

core/models.py
from django.db import models


class School(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return f"School: {self.name}"


class User(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=30, null=True)

    def __str__(self):
        return self.name


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, verbose_name='Пользователи',)
    login = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    course = models.ManyToManyField(Course, verbose_name='Курсы',)
    school = models.ForeignKey(School, on_delete=models.CASCADE, verbose_name='Школа',)

    def __str__(self):
        return f"Account - {self.user}"

core/forms.py
from django import forms

from core import models


# class AccountSearch(forms.Form):
#     user = forms.CharField(label='Имя пользователя', required=False, help_text='Поиск по имени пользователя', )
#     school = forms.CharField(label='Название школы', required=False, help_text='Поиск по названию школы', )
#
#     def clean(self):
#         user_name = self.cleaned_data['user']
#         school_name = self.cleaned_data['school']
#         if user_name or school_name in '''@/*#!$%^?\[]-_)+=;`~.,<>'"|''':
#             raise forms.ValidationError('Невозможные символы')
#         return


class AccountForm(forms.ModelForm):
    login = forms.CharField(label='Логин', required=True)
    password = forms.CharField(label='Пароль', required=True)

    def clean_login(self):
        login = self.cleaned_data['login']
        if login.isnumeric():
            raise forms.ValidationError('Логин не должен состоять только из чисел')
        return login

    class Meta:
        model = models.Account
        fields = '__all__'

core/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from core import models, datatools, forms, filters
from .datatools.index import *


# def get_account_list(request):
#     # поиск по ID
#     user_id = request.GET.get('user_id')
#     if user_id:
#         accounts = models.Account.objects.filter(user_id__exact=user_id)
#     else:
#         accounts = models.Account.objects.all()
#     context = {'accounts': accounts}
#     return render(request=request, template_name='core/account_list.html', context=context)


class AccountList(TitleMixin, ListView):
    model = models.Account
    template_name = 'core/account_list.html'
    context_object_name = 'accounts'
    title = 'Список аккаунтов'

    def get_filters(self):
        return filters.AccountSearch(self.request.GET)

    def get_queryset(self):
        # фильтр с помощью встроенного функционала
        # user = self.request.GET.get('user')
        # school = self.request.GET.get('school')
        # acc = models.Account.objects.all()
        # if user or school:
        #     return acc.filter(user__name__icontains=user, school__name__icontains=school)
        # return acc
        return self.get_filters().qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.get_filters()
        # context['form_search'] = forms.AccountSearch(self.request.GET or None)
        return context


class AccountDetail(TitleMixin, DetailView):
    model = models.Account
    template_name = 'core/account_detail.html'
    context_object_name = 'account'
    title = 'Детальный аккаунт'


class AccountCreate(TitleMixin, CreateView):
    model = models.Account
    template_name = 'core/account_create.html'
    form_class = forms.AccountForm
    title = 'Создание аккаунта'
    success_url = reverse_lazy('core:accounts')


class AccountUpdate(TitleMixin, UpdateView):
    model = models.Account
    template_name = 'core/account_update.html'
    form_class = forms.AccountForm
    title = 'Обновление аккаунта'
    success_url = reverse_lazy('core:accounts')


class AccountDelete(TitleMixin, DeleteView):
    model = models.User
    template_name = 'core/account_delete.html'
    fields = "__all__"
    title = 'Удаление пользователя'
    success_url = reverse_lazy('core:accounts')


def get_main_page(request):
    return render(request=request, template_name='core/main.html')

# def get_account_detail(request, pk):
#     account = get_object_or_404(models.Account, pk=pk)
# Велосипед по изъятию значений из queryset, от которого удалось избавиться
#     count_courses = account.course.all().count()
#     course = account.course.all()
#     name_course = ' '
#     for one_course in range(count_courses):
#         name_course = name_course + course[one_course].name + '; '
# Конец велосипеда
#     context = {'account': account, 'courses': name_course}
#     return render(request=request, template_name='core/account_detail.html', context=context)

core/templates/core/account_create.html
{% extends 'core/base.html' %}
{% if request.user.is_superuser %}
{% block title %} {{ title }} {% endblock %}<
{% block content %}
    <h1>Создание аккаунта пользователя</h1>
    <form action="{% url 'core:account_create' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success" type="submit">Создать</button>
        <a class="btn btn-secondary" href="{% url 'core:accounts' %}" role="button">Вернуться к аккаунтам</a>
    </form>
{% endblock %}
{% endif %}

core/templates/core/account_delete.html
{% extends 'core/base.html' %}
{% if request.user.is_superuser %}
{% block title %} {{ title }} {% endblock %}<
{% block content %}
    <h1>Удалить пользователя {{ user.name }}?</h1>
    <form action="{% url 'core:account_delete' pk=user.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-danger" type="submit">Удалить</button>
        <a class="btn btn-secondary" href="{% url 'core:accounts' %}" role="button">Вернуться к аккаунтам</a>
    </form>
{% endblock %}
{% endif %}

core/templates/core/account_detail.html
{% extends 'core/base.html' %}
{% if request.user.is_superuser %}
{% block title %} {{ title }} {% endblock %}<
{% block content %}
    <h1>Информация об аккаунте пользователя: {{ account.user }}</h1>
    <h3>ID: {{ account.pk }}</h3>
    <h3>Количество курсов: {{ account.course.count }}</h3>
    <h3>Курсы:</h3>
    <ul>
        {% for course in account.course.all %}
            <li><h3>{{ course }}</h3></li>
        {% empty %}
            <h2>Список курсов пуст</h2>
        {% endfor %}
    </ul>
    <h3>Школа: {{ account.school.name }}</h3>
    <a class="btn btn-secondary" href="{% url 'core:accounts' %}" role="button">Все аккаунты</a>
{% endblock %}
{% endif %}

core/templates/core/account_list.html
{% extends 'core/base.html' %}
{% block title %} {{ title }} {% endblock %}<
{% block content %}
    <h1>Список зарегистрированных пользователей (админу всё достуно (имя - admin, пароль - 1234))</h1>
    <form method="GET">
        {#        {{ form_search }}#}
        {{ filter.form.as_p }}
        <button class="btn btn-warning btn-sm" type="submit" role="button">Поиск</button>
        <a class="btn btn-secondary btn-sm" href="{% url 'core:accounts' %}" role="button">Сброс</a>
    </form>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">ID пользователя</th>
            <th scope="col">Пользователь</th>
            <th scope="col">Количество курсов</th>
            <th scope="col">Школа пользователя</th>
            {% if request.user.is_superuser %}
                <th scope="col">Подробнее</th>
                <th scope="col">Обновление</th>
                <th scope="col">Удаление</th>
            {% endif %}
        </tr>
        </thead>
        {% for account in accounts %}
            <tbody>
            <tr>
                <td>{{ account.pk }}</td>
                <td>{{ account.user }}</td>
                <td>{{ account.course.count }}</td>
                <td>{{ account.school.name }}</td>
                {% if request.user.is_superuser %}
                    <td><a href="{% url 'core:account_detail' account.pk %}" role="button">Подробнее об акаунте</a></td>
                    <td><a href="{% url 'core:account_update' account.pk %}" role="button">Обновление акаунта</a></td>
                    <td><a href="{% url 'core:account_delete' account.pk %}" role="button">Удаление пользователя</a>
                    </td>
                {% endif %}
            </tr>
            </tbody>
        {% empty %}
            <h3>Список пользователей пуст</h3>
        {% endfor %}
    </table>
    {% if request.user.is_superuser %}
        <a class="btn btn-primary" href="{% url 'core:account_create' %}" role="button">Создание нового аккаунта</a>
    {% endif %}
{% endblock %}

core/templates/core/account_update.html
{% extends 'core/base.html' %}
{% if request.user.is_superuser %}
    {% block title %} {{ title }} {% endblock %}
    {% block content %}
        <h1>Обновление аккаунта пользователя {{ account.user }}</h1>
        <form action="{% url 'core:account_update' pk=account.pk %}" method="POST">
            {% csrf_token %}
            <h4 hidden><p>{{ form.user }}</p></h4>
            <h4><p>{{ form.login.label_tag }}</p></h4>
            <h4><p>{{ form.login }}</p></h4>
            <h4><p>{{ form.login.errors }}</p></h4>
            <h4><p>{{ form.password.label_tag }}</p></h4>
            <h4><p>{{ form.password }}</p></h4>
            <h4><p>{{ form.course.label_tag }}</p></h4>
            <h4><p>{{ form.course }}</p></h4>
            <h4><p>{{ form.school.label_tag }}</p></h4>
            <h4><p>{{ form.school }}</p></h4>
            <button class="btn btn-success" type="submit">Обновить</button>
            <a class="btn btn-secondary" href="{% url 'core:accounts' %}" role="button">Вернуться к аккаунтам</a>
        </form>
    {% endblock %}
{% endif %}

core/templates/core/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body>
{% block content %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</body>
</html>

core/templates/core/main.html
{% extends 'core/base.html' %}
{% block title %} Главная {% endblock %}<
{% block content %}
    <h1>Добро пожаловать (админу всё достуно (имя - admin, пароль - 1234))</h1>
    <ul>
        <li><h3><a href="{% url 'core:accounts' %}" role="button">Список пользователей</a></h3></li>
        {% if request.user.is_superuser %}
            <li><h3><a href="{% url 'core:account_create' %}" role="button">Создание пользователя</a></h3></li>
        {% endif %}
    </ul>
{% endblock %}